import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // sidebar1: [{type: 'autogenerated', dirName: '1'}],

  // But you can create a sidebar manually
  sidebar1: [
    {
      type: 'category',
      label: 'Äidinkieli 1',
      items: [
        {
          type: 'doc',
          id: '1/aidinkieli/suomen',
        },
        {
          type: 'doc',
          id: '1/aidinkieli/saamen',
        },
        {
          type: 'doc',
          id: '1/aidinkieli/romanikielen',
        },
        {
          type: 'doc',
          id: '1/aidinkieli/suomen-toisena',
        },
        {
          type: 'doc',
          id: '1/aidinkieli/viittomakielen',
        },
      ],
    },
    {
      type: 'category',
      label: 'Toinen kotimainen 1',
      items: [
        {
          type: 'doc',
          id: '1/toinen/ruotsi-a',
        },
        {
          type: 'doc',
          id: '1/toinen/ruotsi-a1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Vieraat kielet 1',
      items: [
        {
          type: 'doc',
          id: '1/vieraat/englanti-a',
        },
        {
          type: 'doc',
          id: '1/vieraat/saame-a',
        },
        {
          type: 'doc',
          id: '1/vieraat/saame-a1',
        },
      ],
    },
    {
      type: 'doc',
      id: '1/matematiikka',
    },
    {
      type: 'doc',
      id: '1/musiikki',
    },
    {
      type: 'doc',
      id: '1/kasityo',
    },
    {
      type: 'doc',
      id: '1/kuvataide',
    },
    {
      type: 'doc',
      id: '1/ymparistooppi',
    },
    {
      type: 'doc',
      id: '1/elamankatsomustieto',
    },
    {
      type: 'category',
      label: 'Uskonto 1',
      items: [
        {
          type: 'doc',
          id: '1/uskonto/adventistinen',
        },
        {
          type: 'doc',
          id: '1/uskonto/bahai',
        },
        {
          type: 'doc',
          id: '1/uskonto/buddhalainen',
        },
        {
          type: 'doc',
          id: '1/uskonto/evankelisluterilainen',
        },
        {
          type: 'doc',
          id: '1/uskonto/helluntailiikkeen',
        },
        {
          type: 'doc',
          id: '1/uskonto/islam',
        },
        {
          type: 'doc',
          id: '1/uskonto/juutalainen',
        },
        {
          type: 'doc',
          id: '1/uskonto/katolinen',
        },
        {
          type: 'doc',
          id: '1/uskonto/krishna',
        },
        {
          type: 'doc',
          id: '1/uskonto/ortodoksinen',
        },
      ],
    },
    {
      type: 'doc',
      id: '1/liikunta',
    },
    {
      type: 'doc',
      id: '1/tulevaisuus',
    },
  ],

  sidebar2: [
    {
      type: 'category',
      label: 'Äidinkieli 2',
      items: [
        {
          type: 'doc',
          id: '2/aidinkieli/suomen',
        },
        {
          type: 'doc',
          id: '2/aidinkieli/saamen',
        },
        {
          type: 'doc',
          id: '2/aidinkieli/romanikielen',
        },
        {
          type: 'doc',
          id: '2/aidinkieli/suomen-toisena',
        },
        {
          type: 'doc',
          id: '2/aidinkieli/viittomakielen',
        },
      ],
    },
    {
      type: 'category',
      label: 'Toinen kotimainen 2',
      items: [
        {
          type: 'doc',
          id: '2/toinen/ruotsi-a',
        },
        {
          type: 'doc',
          id: '2/toinen/ruotsi-a1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Vieraat kielet 2',
      items: [
        {
          type: 'doc',
          id: '2/vieraat/englanti-a',
        },
        {
          type: 'doc',
          id: '2/vieraat/saame-a',
        },
        {
          type: 'doc',
          id: '2/vieraat/saame-a1',
        },
      ],
    },
    {
      type: 'doc',
      id: '2/matematiikka',
    },
    {
      type: 'doc',
      id: '2/musiikki',
    },
    {
      type: 'doc',
      id: '2/kasityo',
    },
    {
      type: 'doc',
      id: '2/kuvataide',
    },
    {
      type: 'doc',
      id: '2/ymparistooppi',
    },
    {
      type: 'doc',
      id: '2/elamankatsomustieto',
    },
    {
      type: 'category',
      label: 'Uskonto 2',
      items: [
        {
          type: 'doc',
          id: '2/uskonto/adventistinen',
        },
        {
          type: 'doc',
          id: '2/uskonto/bahai',
        },
        {
          type: 'doc',
          id: '2/uskonto/buddhalainen',
        },
        {
          type: 'doc',
          id: '2/uskonto/evankelisluterilainen',
        },
        {
          type: 'doc',
          id: '2/uskonto/helluntailiikkeen',
        },
        {
          type: 'doc',
          id: '2/uskonto/islam',
        },
        {
          type: 'doc',
          id: '2/uskonto/juutalainen',
        },
        {
          type: 'doc',
          id: '2/uskonto/katolinen',
        },
        {
          type: 'doc',
          id: '2/uskonto/krishna',
        },
        {
          type: 'doc',
          id: '2/uskonto/ortodoksinen',
        },
      ],
    },
    {
      type: 'doc',
      id: '2/liikunta',
    },
    {
      type: 'doc',
      id: '2/tulevaisuus',
    },
  ],
  sidebar3: [
    {
      type: 'category',
      label: 'Äidinkieli 3',
      items: [
        {
          type: 'doc',
          id: '3/aidinkieli/suomen',
        },
        {
          type: 'doc',
          id: '3/aidinkieli/saamen',
        },
        {
          type: 'doc',
          id: '3/aidinkieli/romanikielen',
        },
        {
          type: 'doc',
          id: '3/aidinkieli/suomen-toisena',
        },
        {
          type: 'doc',
          id: '3/aidinkieli/viittomakielen',
        },
      ],
    },
    {
      type: 'category',
      label: 'Toinen kotimainen 3',
      items: [
        {
          type: 'doc',
          id: '3/toinen/ruotsi-a',
        },
        {
          type: 'doc',
          id: '3/toinen/ruotsi-b1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Vieraat kielet 3',
      items: [
        {
          type: 'doc',
          id: '3/vieraat/englanti-a',
        },
        {
          type: 'doc',
          id: '3/vieraat/saame-a',
        },
      ],
    },
    {
      type: 'doc',
      id: '3/matematiikka',
    },
    {
      type: 'doc',
      id: '3/musiikki',
    },
    {
      type: 'doc',
      id: '3/kasityo',
    },
    {
      type: 'doc',
      id: '3/kuvataide',
    },
    {
      type: 'doc',
      id: '3/ymparistooppi',
    },
    {
      type: 'doc',
      id: '3/historia',
    },
    {
      type: 'doc',
      id: '3/yhteiskuntaoppi',
    },
    {
      type: 'doc',
      id: '3/elamankatsomustieto',
    },
    {
      type: 'category',
      label: 'Uskonto 3',
      items: [
        {
          type: 'doc',
          id: '3/uskonto/adventistinen',
        },
        {
          type: 'doc',
          id: '3/uskonto/bahai',
        },
        {
          type: 'doc',
          id: '3/uskonto/buddhalainen',
        },
        {
          type: 'doc',
          id: '3/uskonto/evankelisluterilainen',
        },
        {
          type: 'doc',
          id: '3/uskonto/helluntailiikkeen',
        },
        {
          type: 'doc',
          id: '3/uskonto/islam',
        },
        {
          type: 'doc',
          id: '3/uskonto/juutalainen',
        },
        {
          type: 'doc',
          id: '3/uskonto/katolinen',
        },
        {
          type: 'doc',
          id: '3/uskonto/krishna',
        },
        {
          type: 'doc',
          id: '3/uskonto/ortodoksinen',
        },
      ],
    },
    {
      type: 'doc',
      id: '3/liikunta',
    },
    {
      type: 'doc',
      id: '3/tulevaisuus',
    },
  ],
  sidebar4: [
    {
      type: 'category',
      label: 'Äidinkieli 4',
      items: [
        {
          type: 'doc',
          id: '4/aidinkieli/suomen',
        },
        {
          type: 'doc',
          id: '4/aidinkieli/saamen',
        },
        {
          type: 'doc',
          id: '4/aidinkieli/romanikielen',
        },
        {
          type: 'doc',
          id: '4/aidinkieli/suomen-toisena',
        },
        {
          type: 'doc',
          id: '4/aidinkieli/viittomakielen',
        },
      ],
    },
    {
      type: 'category',
      label: 'Toinen kotimainen 4',
      items: [
        {
          type: 'doc',
          id: '4/toinen/ruotsi-a',
        },
        {
          type: 'doc',
          id: '4/toinen/ruotsi-b1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Vieraat kielet 4',
      items: [
        {
          type: 'doc',
          id: '4/vieraat/englanti-a',
        },
        {
          type: 'doc',
          id: '4/vieraat/saame-a',
        },
      ],
    },
    {
      type: 'doc',
      id: '4/matematiikka',
    },
    {
      type: 'doc',
      id: '4/musiikki',
    },
    {
      type: 'doc',
      id: '4/kasityo',
    },
    {
      type: 'doc',
      id: '4/kuvataide',
    },
    {
      type: 'doc',
      id: '4/ymparistooppi',
    },
    {
      type: 'doc',
      id: '4/historia',
    },
    {
      type: 'doc',
      id: '4/yhteiskuntaoppi',
    },
    {
      type: 'doc',
      id: '4/elamankatsomustieto',
    },
    {
      type: 'category',
      label: 'Uskonto 4',
      items: [
        {
          type: 'doc',
          id: '4/uskonto/adventistinen',
        },
        {
          type: 'doc',
          id: '4/uskonto/bahai',
        },
        {
          type: 'doc',
          id: '4/uskonto/buddhalainen',
        },
        {
          type: 'doc',
          id: '4/uskonto/evankelisluterilainen',
        },
        {
          type: 'doc',
          id: '4/uskonto/helluntailiikkeen',
        },
        {
          type: 'doc',
          id: '4/uskonto/islam',
        },
        {
          type: 'doc',
          id: '4/uskonto/juutalainen',
        },
        {
          type: 'doc',
          id: '4/uskonto/katolinen',
        },
        {
          type: 'doc',
          id: '4/uskonto/krishna',
        },
        {
          type: 'doc',
          id: '4/uskonto/ortodoksinen',
        },
      ],
    },
    {
      type: 'doc',
      id: '4/liikunta',
    },
    {
      type: 'doc',
      id: '4/tulevaisuus',
    },
  ],
  sidebar5: [
    {
      type: 'category',
      label: 'Äidinkieli 5',
      items: [
        {
          type: 'doc',
          id: '5/aidinkieli/suomen',
        },
        {
          type: 'doc',
          id: '5/aidinkieli/saamen',
        },
        {
          type: 'doc',
          id: '5/aidinkieli/romanikielen',
        },
        {
          type: 'doc',
          id: '5/aidinkieli/suomen-toisena',
        },
        {
          type: 'doc',
          id: '5/aidinkieli/viittomakielen',
        },
      ],
    },
    {
      type: 'category',
      label: 'Toinen kotimainen 5',
      items: [
        {
          type: 'doc',
          id: '5/toinen/ruotsi-a',
        },
        {
          type: 'doc',
          id: '5/toinen/ruotsi-b1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Vieraat kielet 5',
      items: [
        {
          type: 'doc',
          id: '5/vieraat/englanti-a',
        },
        {
          type: 'doc',
          id: '5/vieraat/saame-a',
        },
      ],
    },
    {
      type: 'doc',
      id: '5/matematiikka',
    },
    {
      type: 'doc',
      id: '5/musiikki',
    },
    {
      type: 'doc',
      id: '5/kasityo',
    },
    {
      type: 'doc',
      id: '5/kuvataide',
    },
    {
      type: 'doc',
      id: '5/ymparistooppi',
    },
    {
      type: 'doc',
      id: '5/historia',
    },
    {
      type: 'doc',
      id: '5/yhteiskuntaoppi',
    },
    {
      type: 'doc',
      id: '5/elamankatsomustieto',
    },
    {
      type: 'category',
      label: 'Uskonto 5',
      items: [
        {
          type: 'doc',
          id: '5/uskonto/adventistinen',
        },
        {
          type: 'doc',
          id: '5/uskonto/bahai',
        },
        {
          type: 'doc',
          id: '5/uskonto/buddhalainen',
        },
        {
          type: 'doc',
          id: '5/uskonto/evankelisluterilainen',
        },
        {
          type: 'doc',
          id: '5/uskonto/helluntailiikkeen',
        },
        {
          type: 'doc',
          id: '5/uskonto/islam',
        },
        {
          type: 'doc',
          id: '5/uskonto/juutalainen',
        },
        {
          type: 'doc',
          id: '5/uskonto/katolinen',
        },
        {
          type: 'doc',
          id: '5/uskonto/krishna',
        },
        {
          type: 'doc',
          id: '5/uskonto/ortodoksinen',
        },
      ],
    },
    {
      type: 'doc',
      id: '5/liikunta',
    },
    {
      type: 'doc',
      id: '5/tulevaisuus',
    },
  ],
  sidebar6: [
    {
      type: 'category',
      label: 'Äidinkieli 6',
      items: [
        {
          type: 'doc',
          id: '6/aidinkieli/suomen',
        },
        {
          type: 'doc',
          id: '6/aidinkieli/saamen',
        },
        {
          type: 'doc',
          id: '6/aidinkieli/romanikielen',
        },
        {
          type: 'doc',
          id: '6/aidinkieli/suomen-toisena',
        },
        {
          type: 'doc',
          id: '6/aidinkieli/viittomakielen',
        },
      ],
    },
    {
      type: 'category',
      label: 'Toinen kotimainen 6',
      items: [
        {
          type: 'doc',
          id: '6/toinen/ruotsi-a',
        },
        {
          type: 'doc',
          id: '6/toinen/ruotsi-b1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Vieraat kielet 6',
      items: [
        {
          type: 'doc',
          id: '6/vieraat/englanti-a',
        },
        {
          type: 'doc',
          id: '6/vieraat/saame-a',
        },
      ],
    },
    {
      type: 'doc',
      id: '6/matematiikka',
    },
    {
      type: 'doc',
      id: '6/musiikki',
    },
    {
      type: 'doc',
      id: '6/kasityo',
    },
    {
      type: 'doc',
      id: '6/kuvataide',
    },
    {
      type: 'doc',
      id: '6/ymparistooppi',
    },
    {
      type: 'doc',
      id: '6/historia',
    },
    {
      type: 'doc',
      id: '6/yhteiskuntaoppi',
    },
    {
      type: 'doc',
      id: '6/elamankatsomustieto',
    },
    {
      type: 'category',
      label: 'Uskonto 6',
      items: [
        {
          type: 'doc',
          id: '6/uskonto/adventistinen',
        },
        {
          type: 'doc',
          id: '6/uskonto/bahai',
        },
        {
          type: 'doc',
          id: '6/uskonto/buddhalainen',
        },
        {
          type: 'doc',
          id: '6/uskonto/evankelisluterilainen',
        },
        {
          type: 'doc',
          id: '6/uskonto/helluntailiikkeen',
        },
        {
          type: 'doc',
          id: '6/uskonto/islam',
        },
        {
          type: 'doc',
          id: '6/uskonto/juutalainen',
        },
        {
          type: 'doc',
          id: '6/uskonto/katolinen',
        },
        {
          type: 'doc',
          id: '6/uskonto/krishna',
        },
        {
          type: 'doc',
          id: '6/uskonto/ortodoksinen',
        },
      ],
    },
    {
      type: 'doc',
      id: '6/liikunta',
    },
    {
      type: 'doc',
      id: '6/tulevaisuus',
    },
  ],
  sidebar7: [
    {
      type: 'category',
      label: 'Äidinkieli 7',
      items: [
        {
          type: 'doc',
          id: '7/aidinkieli/suomen',
        },
        {
          type: 'doc',
          id: '7/aidinkieli/saamen',
        },
        {
          type: 'doc',
          id: '7/aidinkieli/romanikielen',
        },
        {
          type: 'doc',
          id: '7/aidinkieli/suomen-toisena',
        },
        {
          type: 'doc',
          id: '7/aidinkieli/viittomakielen',
        },
      ],
    },
    {
      type: 'category',
      label: 'Toinen kotimainen 7',
      items: [
        {
          type: 'doc',
          id: '7/toinen/ruotsi-a',
        },
        {
          type: 'doc',
          id: '7/toinen/ruotsi-b1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Vieraat kielet 7',
      items: [
        {
          type: 'doc',
          id: '7/vieraat/englanti-a',
        },
        {
          type: 'doc',
          id: '7/vieraat/saame-a',
        },
        {
          type: 'doc',
          id: '7/vieraat/saame-b2',
        },
        {
          type: 'doc',
          id: '7/vieraat/latina-b2',
        },
      ],
    },
    {
      type: 'doc',
      id: '7/matematiikka',
    },
    {
      type: 'doc',
      id: '7/maantieto',
    },
    {
      type: 'doc',
      id: '7/fysiikka',
    },
    {
      type: 'doc',
      id: '7/kemia',
    },
    {
      type: 'doc',
      id: '7/musiikki',
    },
    {
      type: 'doc',
      id: '7/kasityo',
    },
    {
      type: 'doc',
      id: '7/kuvataide',
    },
    {
      type: 'doc',
      id: '7/biologia',
    },
    {
      type: 'doc',
      id: '7/historia',
    },
    {
      type: 'doc',
      id: '7/yhteiskuntaoppi',
    },
    {
      type: 'doc',
      id: '7/kotitalous',
    },
    {
      type: 'doc',
      id: '7/terveystieto',
    },
    {
      type: 'doc',
      id: '7/elamankatsomustieto',
    },
    {
      type: 'category',
      label: 'Uskonto 7',
      items: [
        {
          type: 'doc',
          id: '7/uskonto/adventistinen',
        },
        {
          type: 'doc',
          id: '7/uskonto/bahai',
        },
        {
          type: 'doc',
          id: '7/uskonto/buddhalainen',
        },
        {
          type: 'doc',
          id: '7/uskonto/evankelisluterilainen',
        },
        {
          type: 'doc',
          id: '7/uskonto/helluntailiikkeen',
        },
        {
          type: 'doc',
          id: '7/uskonto/islam',
        },
        {
          type: 'doc',
          id: '7/uskonto/juutalainen',
        },
        {
          type: 'doc',
          id: '7/uskonto/katolinen',
        },
        {
          type: 'doc',
          id: '7/uskonto/krishna',
        },
        {
          type: 'doc',
          id: '7/uskonto/ortodoksinen',
        },
      ],
    },
    {
      type: 'doc',
      id: '7/liikunta',
    },
    {
      type: 'doc',
      id: '7/tulevaisuus',
    },
  ],
  sidebar8: [
    {
      type: 'category',
      label: 'Äidinkieli 8',
      items: [
        {
          type: 'doc',
          id: '8/aidinkieli/suomen',
        },
        {
          type: 'doc',
          id: '8/aidinkieli/saamen',
        },
        {
          type: 'doc',
          id: '8/aidinkieli/romanikielen',
        },
        {
          type: 'doc',
          id: '8/aidinkieli/suomen-toisena',
        },
        {
          type: 'doc',
          id: '8/aidinkieli/viittomakielen',
        },
      ],
    },
    {
      type: 'category',
      label: 'Toinen kotimainen 8',
      items: [
        {
          type: 'doc',
          id: '8/toinen/ruotsi-a',
        },
        {
          type: 'doc',
          id: '8/toinen/ruotsi-b1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Vieraat kielet 8',
      items: [
        {
          type: 'doc',
          id: '8/vieraat/englanti-a',
        },
        {
          type: 'doc',
          id: '8/vieraat/saame-a',
        },
        {
          type: 'doc',
          id: '8/vieraat/saame-b2',
        },
        {
          type: 'doc',
          id: '8/vieraat/latina-b2',
        },
      ],
    },
    {
      type: 'doc',
      id: '8/matematiikka',
    },
    {
      type: 'doc',
      id: '8/maantieto',
    },
    {
      type: 'doc',
      id: '8/fysiikka',
    },
    {
      type: 'doc',
      id: '8/kemia',
    },
    {
      type: 'doc',
      id: '8/musiikki',
    },
    {
      type: 'doc',
      id: '8/kasityo',
    },
    {
      type: 'doc',
      id: '8/kuvataide',
    },
    {
      type: 'doc',
      id: '8/biologia',
    },
    {
      type: 'doc',
      id: '8/historia',
    },
    {
      type: 'doc',
      id: '8/yhteiskuntaoppi',
    },
    {
      type: 'doc',
      id: '8/kotitalous',
    },
    {
      type: 'doc',
      id: '8/terveystieto',
    },
    {
      type: 'doc',
      id: '8/elamankatsomustieto',
    },
    {
      type: 'category',
      label: 'Uskonto 8',
      items: [
        {
          type: 'doc',
          id: '8/uskonto/adventistinen',
        },
        {
          type: 'doc',
          id: '8/uskonto/bahai',
        },
        {
          type: 'doc',
          id: '8/uskonto/buddhalainen',
        },
        {
          type: 'doc',
          id: '8/uskonto/evankelisluterilainen',
        },
        {
          type: 'doc',
          id: '8/uskonto/helluntailiikkeen',
        },
        {
          type: 'doc',
          id: '8/uskonto/islam',
        },
        {
          type: 'doc',
          id: '8/uskonto/juutalainen',
        },
        {
          type: 'doc',
          id: '8/uskonto/katolinen',
        },
        {
          type: 'doc',
          id: '8/uskonto/krishna',
        },
        {
          type: 'doc',
          id: '8/uskonto/ortodoksinen',
        },
      ],
    },
    {
      type: 'doc',
      id: '8/liikunta',
    },
    {
      type: 'doc',
      id: '8/tulevaisuus',
    },
  ],
  sidebar9: [
    {
      type: 'category',
      label: 'Äidinkieli 9',
      items: [
        {
          type: 'doc',
          id: '9/aidinkieli/suomen',
        },
        {
          type: 'doc',
          id: '9/aidinkieli/saamen',
        },
        {
          type: 'doc',
          id: '9/aidinkieli/romanikielen',
        },
        {
          type: 'doc',
          id: '9/aidinkieli/suomen-toisena',
        },
        {
          type: 'doc',
          id: '9/aidinkieli/viittomakielen',
        },
      ],
    },
    {
      type: 'category',
      label: 'Toinen kotimainen 9',
      items: [
        {
          type: 'doc',
          id: '9/toinen/ruotsi-a',
        },
        {
          type: 'doc',
          id: '9/toinen/ruotsi-b1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Vieraat kielet 9',
      items: [
        {
          type: 'doc',
          id: '9/vieraat/englanti-a',
        },
        {
          type: 'doc',
          id: '9/vieraat/saame-a',
        },
        {
          type: 'doc',
          id: '9/vieraat/saame-b2',
        },
        {
          type: 'doc',
          id: '9/vieraat/latina-b2',
        },
      ],
    },
    {
      type: 'doc',
      id: '9/matematiikka',
    },
    {
      type: 'doc',
      id: '9/maantieto',
    },
    {
      type: 'doc',
      id: '9/fysiikka',
    },
    {
      type: 'doc',
      id: '9/kemia',
    },
    {
      type: 'doc',
      id: '9/musiikki',
    },
    {
      type: 'doc',
      id: '9/kasityo',
    },
    {
      type: 'doc',
      id: '9/kuvataide',
    },
    {
      type: 'doc',
      id: '9/biologia',
    },
    {
      type: 'doc',
      id: '9/historia',
    },
    {
      type: 'doc',
      id: '9/yhteiskuntaoppi',
    },
    {
      type: 'doc',
      id: '9/kotitalous',
    },
    {
      type: 'doc',
      id: '9/terveystieto',
    },
    {
      type: 'doc',
      id: '9/elamankatsomustieto',
    },
    {
      type: 'category',
      label: 'Uskonto 9',
      items: [
        {
          type: 'doc',
          id: '9/uskonto/adventistinen',
        },
        {
          type: 'doc',
          id: '9/uskonto/bahai',
        },
        {
          type: 'doc',
          id: '9/uskonto/buddhalainen',
        },
        {
          type: 'doc',
          id: '9/uskonto/evankelisluterilainen',
        },
        {
          type: 'doc',
          id: '9/uskonto/helluntailiikkeen',
        },
        {
          type: 'doc',
          id: '9/uskonto/islam',
        },
        {
          type: 'doc',
          id: '9/uskonto/juutalainen',
        },
        {
          type: 'doc',
          id: '9/uskonto/katolinen',
        },
        {
          type: 'doc',
          id: '9/uskonto/krishna',
        },
        {
          type: 'doc',
          id: '9/uskonto/ortodoksinen',
        },
      ],
    },
    {
      type: 'doc',
      id: '9/liikunta',
    },
    {
      type: 'doc',
      id: '9/tulevaisuus',
    },
  ],
};

export default sidebars;
